# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-25 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isodur_app', '0004_section_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
