# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isodur_app', '0007_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='word_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='word_fr',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='word_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='content_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='content_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='feedback_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='feedback_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='feedback_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='title_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='title_fr',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='title_ru',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
