# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-18 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isodur_app', '0009_sectiondropdownfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectiondropdownfield',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='isodur_app.Section'),
        ),
    ]
