# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-24 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isodur_app', '0010_auto_20170318_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='word_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='content_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='feedback_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='project',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='section',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='section',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='sectiondropdownfield',
            name='title_ru',
        ),
        migrations.AddField(
            model_name='productphoto',
            name='product_main_photo',
            field=models.ImageField(blank=True, null=True, upload_to='product_main_photo'),
        ),
    ]
