# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-24 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isodur_app', '0011_auto_20170324_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productphoto',
            name='product_main_photo',
            field=models.ImageField(blank=True, null=True, upload_to='product_photo'),
        ),
    ]
