# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-24 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isodur_app', '0012_auto_20170324_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productphoto',
            name='product_main_photo',
        ),
        migrations.AddField(
            model_name='product',
            name='product_main_photo',
            field=models.ImageField(blank=True, null=True, upload_to='product_photo'),
        ),
    ]
