# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-27 13:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isodur_app', '0013_auto_20170324_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productphoto',
            name='add_to_slider',
        ),
    ]
