# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-27 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isodur_app', '0014_remove_productphoto_add_to_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageRedirectionPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
