# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-27 14:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isodur_app', '0017_auto_20170327_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyword',
            old_name='word_en_US',
            new_name='word_en',
        ),
        migrations.RenameField(
            model_name='keyword',
            old_name='word_fr_FR',
            new_name='word_fr',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='content_en_US',
            new_name='content_en',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='content_fr_FR',
            new_name='content_fr',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='feedback_en_US',
            new_name='feedback_en',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='feedback_fr_FR',
            new_name='feedback_fr',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name_en_US',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name_fr_FR',
            new_name='name_fr',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='title_en_US',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='title_fr_FR',
            new_name='title_fr',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='description_en_US',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='description_fr_FR',
            new_name='description_fr',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='title_en_US',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='title_fr_FR',
            new_name='title_fr',
        ),
        migrations.RenameField(
            model_name='sectiondropdownfield',
            old_name='title_en_US',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='sectiondropdownfield',
            old_name='title_fr_FR',
            new_name='title_fr',
        ),
    ]
