# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-07 11:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isodur_app', '0018_auto_20170327_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_photo', models.ImageField(blank=True, null=True, upload_to='project_photo')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='isodur_app.Project')),
            ],
        ),
    ]
