# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-07 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isodur_app', '0020_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerimage',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='isodur_app.Partner'),
        ),
        migrations.AlterField(
            model_name='partnerimage',
            name='project_photo',
            field=models.ImageField(blank=True, null=True, upload_to='partner_photo'),
        ),
    ]
