# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-07 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isodur_app', '0023_auto_20170407_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerimage',
            name='partner',
        ),
        migrations.AddField(
            model_name='partner',
            name='partners',
            field=models.ImageField(blank=True, null=True, upload_to='partners'),
        ),
        migrations.DeleteModel(
            name='PartnerImage',
        ),
    ]
