# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-07 17:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isodur_app', '0024_auto_20170407_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='partners',
            new_name='image_part',
        ),
    ]
