# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-07 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isodur_app', '0025_auto_20170407_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='image_part',
        ),
        migrations.AddField(
            model_name='partner',
            name='partner_image',
            field=models.ImageField(blank=True, null=True, upload_to='partner_image'),
        ),
    ]
