# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-07 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isodur_app', '0026_auto_20170407_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='partner_image',
            field=models.ImageField(blank=True, null=True, upload_to='partners'),
        ),
    ]
