# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-11 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isodur_app', '0027_auto_20170407_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='section',
        ),
        migrations.RemoveField(
            model_name='product',
            name='section',
        ),
        migrations.RemoveField(
            model_name='sectiondropdownfield',
            name='section',
        ),
        migrations.RenameField(
            model_name='productphoto',
            old_name='product_photo',
            new_name='project_photo',
        ),
        migrations.RemoveField(
            model_name='productphoto',
            name='product',
        ),
        migrations.RemoveField(
            model_name='project',
            name='section',
        ),
        migrations.DeleteModel(
            name='Keyword',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.DeleteModel(
            name='SectionDropdownField',
        ),
        migrations.AddField(
            model_name='productphoto',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='isodur_app.Product1'),
        ),
    ]
