# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-11 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isodur_app', '0028_auto_20170411_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productphoto',
            name='project',
        ),
        migrations.AddField(
            model_name='product1',
            name='product_photo',
            field=models.ImageField(blank=True, null=True, upload_to='product_photo'),
        ),
        migrations.DeleteModel(
            name='ProductPhoto',
        ),
    ]
