# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-11 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isodur_app', '0030_auto_20170411_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product1',
            name='products',
        ),
        migrations.AddField(
            model_name='product1',
            name='products_photo',
            field=models.ImageField(blank=True, null=True, upload_to='products_photo'),
        ),
    ]
